var associacoes = [
    {nome: 'L.U.C.F.M.', foto:'http://lucfm.000webhostapp.com/imagem/associacao/lucfm.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {nome: 'Arena a gol', foto:'http://lucfm.000webhostapp.com/imagem/associacao/sem.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {nome: 'A.F.U.M.E.P.A.', foto:'http://lucfm.000webhostapp.com/imagem/associacao/afumepa.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {nome: 'POA FM', foto:'http://lucfm.000webhostapp.com/imagem/associacao/sem.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {nome: 'Zona Sul', foto:'http://lucfm.000webhostapp.com/imagem/associacao/zonasul.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {nome: 'A.V.F.B.', foto:'http://lucfm.000webhostapp.com/imagem/associacao/avmf.png',pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
]
var jogadores = [
    {grupo : "A",tecnico: "Cesar Motta",foto: "https://logodetimes.com/times/sao-paulo/logo-sao-paulo-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Rodrigo",foto: "https://logodetimes.com/times/estudiantes-de-la-plata/estudiantes-de-la-plata-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Fábio Fontes",foto: "https://logodetimes.com/times/cruzeiro/logo-cruzeiro-256.png",associacao: associacoes[2].nome,imagem: associacoes[2].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Dirceu",foto: "https://logodetimes.com/times/talleres/logo-talleres-256.png",associacao: associacoes[3].nome,imagem: associacoes[3].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Claúdio",foto: "https://logodetimes.com/times/gremio/logo-gremio-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "André Schimidt",foto: "https://www.campeoesdofutebol.com.br/imagens/pelotas_rs.gif",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Régis",foto: "https://logodetimes.com/times/sao-paulo-do-rio-grande/logo-sao-paulo-do-rio-grande-256.png",associacao: associacoes[2].nome,imagem: associacoes[2].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Polegar",foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Escudo_del_Club_Almagro.svg/375px-Escudo_del_Club_Almagro.svg.png",associacao: associacoes[3].nome,imagem: associacoes[3].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Rafael Botões",foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Cer%C3%A2mica_Atl%C3%A9tico_Clube.png/570px-Cer%C3%A2mica_Atl%C3%A9tico_Clube.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Felipe Rosa",foto: "https://logodetimes.com/times/flamengo/logo-flamengo-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Feliciano Macedo",foto: "https://upload.wikimedia.org/wikipedia/pt/8/83/Esporte_Clube_Igrejinha.png",associacao: associacoes[2].nome,imagem: associacoes[2].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "M. Ocho",foto: "https://logodetimes.com/times/palmeiras/logo-palmeiras-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Motta",foto: "https://logodetimes.com/times/botafogo/logo-botafogo-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Mauricio Rosa",foto: "https://logodetimes.com/times/santos/logo-santos-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Sandro Coelho",foto: "https://logodetimes.com/times/bahia/logo-bahia-256.png",associacao: associacoes[2].nome,imagem: associacoes[2].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Marcelo Ribeiro",foto: "https://logodetimes.com/times/emelec/logo-emelec-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Renato",foto: "https://logodetimes.com/times/internacional/logo-internacional-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "William Kinka",foto: "https://logodetimes.com/times/velez-sarsfield/logo-velez-sarsfield-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Soligo",foto: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Club_acassuso_logo.png",associacao: associacoes[4].nome,imagem: associacoes[4].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Zezinho",foto: "https://upload.wikimedia.org/wikipedia/pt/b/b9/Insignia-union-la-calera.png",associacao: associacoes[5].nome,imagem: associacoes[5].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Ricardo",foto: "https://logodetimes.com/times/atletico-mineiro/logo-atletico-mineiro-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Itálo Bigliardi",foto: "https://logodetimes.com/times/sao-caetano/logo-sao-caetano-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Jamis",foto: "https://logodetimes.com/times/club-atletico-boca-juniors/club-atletico-boca-juniors-256.png",associacao: associacoes[4].nome,imagem: associacoes[4].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Cristaldo",foto: "https://upload.wikimedia.org/wikipedia/pt/6/65/Associa%C3%A7%C3%A3o_Portuguesa_de_Desportos.png",associacao: associacoes[5].nome,imagem: associacoes[5].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Fernando",foto: "https://ssl.gstatic.com/onebox/media/sports/logos/me10ephzRxdj45zVq1Risg_48x48.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Diego Luz",foto: "https://logodetimes.com/times/corinthians/logo-corinthians-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Daniel",foto: "https://logodetimes.com/times/river-plate/logo-river-plate-5.png",associacao: associacoes[4].nome,imagem: associacoes[4].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Carlos Padilha",foto: "https://logodetimes.com/times/criciuma/logo-criciuma-5.png",associacao: associacoes[5].nome,imagem: associacoes[5].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Paulo Marcos",foto: "https://logodetimes.com/times/aldosivi/logo-aldosivi-256.png",associacao: associacoes[0].nome,imagem: associacoes[0].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Jean Soares",foto: "https://logodetimes.com/times/rosario-central/logo-rosario-central-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Diego Fonseca",foto: "https://logodetimes.com/times/colon/logo-colon-256.png",associacao: associacoes[4].nome,imagem: associacoes[4].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Alex Luz",foto: "https://logodetimes.com/times/rosario-central/logo-rosario-central-256.png",associacao: associacoes[1].nome,imagem: associacoes[1].foto,pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0}
]

var jogadoresTotal = jogadores.slice()

var grupo = ['A','B','C','D','E','F','G','H']