var jogadores = [
    {grupo : "A",tecnico: "Cesar Motta",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Rodrigo",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Fábio Fontes",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "A",tecnico: "Dirceu",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Claúdio",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "André Schimidt",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Régis",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "B",tecnico: "Polegar",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Rafael Botões",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Felipe Rosa",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "Feliciano Macedo",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "C",tecnico: "M. Ocho",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Motta",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Mauricio Rosa",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Sandro Coelho",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "D",tecnico: "Marcelo Ribeiro",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Renato",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "William Kinka",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Soligo",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "E",tecnico: "Zezinho",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Ricardo",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Itálo Bigliardi",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Jamis",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "F",tecnico: "Cristaldo",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Fernando",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Diego Luz",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Daniel",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "G",tecnico: "Carlos Padilha",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Paulo Marcos",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Jean Soares",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Diego Fonseca",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0},
    {grupo : "H",tecnico: "Alex Luz",foto: "",associacao: "",imagem: "",pontos:0,jogos:0,vitorias:0,empates:0,derrotas:0,golspro:0,golscontra:0,saldogols:0,aproveitamento:0,desempate:0}
]

var grupo = ['A','B','C','D','E','F','G','H']