var linguagens = [
    { nome: 'HTML e CSS', descricao: 'Projetos com prioridade HTML e CSS.', imagem: 'img/html_css.png', url: 'html-css.html' },
    { nome: 'HTML, CSS e JavaScript', descricao: 'Projetos criado em HTML, CSS e JavaScript.', imagem: 'img/html_css_javascript.png', url: 'html-css-javascript.html' },
    { nome: 'Javascript', descricao: 'Projetos com prioridade em HTML e JavaScript.', imagem: 'img/javascript.png', url: 'javascript.html' },
    { nome: 'P.H.P.', descricao: 'Projetos criado em P.H.P.', imagem: 'img/php.png', url: 'php.html' },
    { nome: 'MySql', descricao: 'Projetos criado em MySql.', imagem: 'img/php.png', url: 'mysql.html' },
    { nome: 'React', descricao: 'Projetos criado em React.', imagem: 'img/react.png', url: 'react.html' },
    { nome: 'Java', descricao: 'Projetos criado em Java.', imagem: 'img/java.png', url: 'java.html' },
    { nome: 'WordPress', descricao: 'Projetos criado em WordPress.', imagem: 'img/wordpress.jpg', url: 'wordpress.html' },
    { nome: 'Flutter', descricao: 'Projetos criado em Flutter.', imagem: 'img/flutter.png', url: 'flutter.html' },
    { nome: 'Python', descricao: 'Projetos criado em Python.', imagem: 'img/python.png', url: 'python.html' },
    { nome: 'Arduino', descricao: 'Projetos em arduino.', imagem: 'img/arquivo.jpg', url: './arduino.html' },
    { nome: 'Android', descricao: 'Projetos em android.', imagem: 'img/arquivo.jpg', url: './android.html' },
    { nome: 'Kotlin', descricao: 'Projetos em Kotlin.', imagem: 'img/arquivo.jpg', url: './kotlin.html' },
    { nome: 'Vite', descricao: 'Projetos em Vite.', imagem: 'img/arquivo.jpg', url: './vite.html' },
    { nome: 'Designer gráfico', descricao: 'Projetos de designer gráfico.', imagem: 'img/arquivo.jpg', url: './imagens/index.html' },
]

var tipos = [
    { nome: 'Site', descricao: 'Tipo site podendo ser o hospedado no servidor.' }, 
    { nome: 'Código', descricao: 'Tipo código podendo ver o código no gitHub.' }, 
    { nome: 'Site Código', descricao: 'Tipo site e código podendo ver o código do site no gitHub.' }
]

var modelos = [
    { nome: 'Dinâmico', descricao: 'Site onde o usúario pode interagir' }, 
    { nome: 'Jogo', descricao: 'Jogos interativos.' }, 
    { nome: 'Não Dinâmico', descricao: 'Site onde o usúario não pode interagir.' }, 
    { nome: 'Código', descricao: 'O usúario só pode ver o código no gitHub' }
]

var projetos = [
    { nome: 'Pessoal', descricao: 'Projeto pessoal.' }, 
    { nome: 'Replicado com mudança', descricao: 'Projeto replicado de um curso ou imersão com pequenas mudanças.' }, 
    { nome: 'Replicado', descricao: 'Projeto replicado de um curso ou imersão sem mudanças' }, 
    { nome: 'Desafio', descricao: 'Pequenos desafios propostos.' }
]

var tags = '#github #desenvolvimentoweb #desenvolvedores #frontend #desenvolvedorfrontend #projetos #oportunidadeprofissional #desenvolvedorjunior #junior #vagas #carreira #remoto'

var tagsLinguagem = ["#HTML #CSS #JAVASCRIPT","#HTML #CSS","#HTML #JAVASCRIPT","#php","#mysql","#react #reactjs","#wordpress","#java","#flutter","#python","#Arduino", "#Android", "#Kotlin", "#designergráfico"]

var sites = [
    // Pessoal
    {titulo: 'Restaurante japonês', descricao: 'Projeto criado no modelo para um restaurante.', linguagem: linguagens[1], url: './sites/restaurante-japones/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} #restaurante`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/restaurante-japones'},
    {titulo: 'Temperatura', descricao: 'Projeto criado no modelo de temperatura.', linguagem: linguagens[1], url: './sites/temperatura/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/temperatura'},
    {titulo: 'Fontes', descricao: 'Projeto criado no modelo para ver fontes.', linguagem: linguagens[0], url: './sites/fontes/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} `, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/fontes'},
    {titulo: 'Skills Bar Animation', descricao: 'Projeto criado no modelo de Skills Bar Animation.', linguagem: linguagens[1], url: './sites/skills-bar-animation/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} #restaurante`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/skills-bar-animation'},
    {titulo: 'Column Property', descricao: 'Projeto criado no modelo de Column Property.', linguagem: linguagens[1], url: './sites/column-property/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} #restaurante`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/column-property'},
    {titulo: 'Poquer', descricao: 'Projeto criado no modelo um jogo de poquer.', linguagem: linguagens[1], url: './sites/poquer/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} #poquer`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/poquer'},
    {titulo: 'Loja', descricao: 'Projeto criado no modelo de uma loja.', linguagem: linguagens[1], url: './sites/loja/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[1]} ${tags} #poquer`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/loja'},
    {titulo: 'Loja - 02', descricao: 'Projeto criado para vendas.', linguagem: linguagens[1], url: 'sites/loja-2/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[0]} ${tags} `, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/loja-2'},
    { titulo: 'Dev midia', descricao: 'Projeto criado no modelo do desafio Dev midia.', linguagem: linguagens[0], url: 'sites/dev-midia/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags} ${tagsLinguagem[0]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/dev-midia'},      
    {titulo: 'Desafio BemPaggo', descricao: 'Projeto criado no modelo do desafio BemPago.', linguagem: linguagens[1], url: 'sites/desafio-bemPaggo/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/desafio-bemPaggo'},
    {titulo: 'Netflix', descricao: 'Projeto criado no modelo da interface da netflix.', linguagem: linguagens[1], url: 'sites/netflix/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #netflix`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/netflix'},
    { titulo: 'Apresentação', descricao: 'Projeto criado no modelo de apresentação', linguagem: linguagens[0], url: 'sites/apresentacao/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[1]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/apresentacao'},  
    {titulo: 'Instagram', descricao: 'Projeto criado no modelo da interface da instagram.', linguagem: linguagens[0], url: 'sites/instagram/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #instagram`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/instagram'},
    {titulo: 'Grid', descricao: 'Projeto criado no modelo de grid.', linguagem: linguagens[0], url: 'sites/grid/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/grid'},
    {titulo: 'Grid 2', descricao: 'Projeto criado no modelo de grid - 2.', linguagem: linguagens[0], url: 'sites/grid-2/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/grid-2'},
    { titulo: 'Tags basicas', descricao: 'Demostração de uma tags HTML.', linguagem: linguagens[0], url: 'sites/tag/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[1]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/tag/'},  
    { titulo: 'JavaScript Dom', descricao: 'Demostração de dom do javascript.', linguagem: linguagens[2], url: 'sites/javascript-dom/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[2]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/javascript-dom/'},
    { titulo: 'Map filter reduce', descricao: 'Demostração de Map filter reduce do javascript.', linguagem: linguagens[2], url: 'sites/map-filter-reduce/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[2]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/map-filter-reduce'},    
    { titulo: 'JavaScript Exemplos', descricao: 'Demostração de exemplos do javascript.', linguagem: linguagens[2], url: 'sites/javascript-exemplos/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[2]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/javascript-exemplos'},    
    { titulo: 'Array JavaScript', descricao: 'Demostração de arrays do javascript.', linguagem: linguagens[2], url: 'sites/array-javascript/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[2]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/array-javascript'},    
    { titulo: 'Segurança de T.I.', descricao: 'Projeto criado para informar a segurança de T.I.', linguagem: linguagens[1], url: 'sites/seguranca-de-ti/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[1]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/seguranca-de-ti'},  
    { titulo: 'Modal', descricao: 'Projeto criado Modal.', linguagem: linguagens[1], url: 'sites/modal/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[1]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/modal'},  
    {titulo: 'Realidade Aumentada', descricao: 'Projeto pessoal criado com passe para mostrar a realidade aumentada.', linguagem: linguagens[0], url: 'sites/realidade-aumentada/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tagsLinguagem[0]} ${tags} #realidadeaumentada`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/realidade-aumentada'},
    /*
    {titulo: 'Snake Game', descricao: 'Projeto criado no modelo do jogo Snake Game do celular.', linguagem: linguagens[0], url: 'sites/html_css_javascript/jogo_snake_game/index.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #games #jogos`, repositorio: ' '},
    {titulo: 'Jogo naves', descricao: 'Projeto criado no modelo do jogo de naves.', linguagem: linguagens[0], url: 'sites/html_css_javascript/jogo_naves/index.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #games #jogos`, repositorio: ' '},
    {titulo: 'Jogo Genius', descricao: 'Projeto criado no modelo do jogo de genius.', linguagem: linguagens[0], url: 'sites/html_css_javascript/jogo_genius/index.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #games #jogos`, repositorio: ' '},
    {titulo: 'Jogo Memoria', descricao: 'Projeto criado no modelo do jogo da memoria.', linguagem: linguagens[0], url: 'sites/html_css_javascript/jogo_memoria/index.html', tipo: tipos[0], modelo: modelos[1], status: 'não', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #games #jogos`, repositorio: ' '},
    {titulo: 'Jogo Scratch', descricao: 'Projeto criado no modelo do jogo da scratch.', linguagem: linguagens[0], url: 'sites/html_css_javascript/jogo_scratch/index.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #games #jogos`, repositorio: ' '},
    */
   { titulo: 'Projetos do P.H.P.', descricao: 'Projeto criado na linguagem P.H.P..', tipo: tipos[0], linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/', modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[3]}`, repositorio: 'https://github.com/clovisbalreira/php'},
   /* 
   { titulo: 'Clube', descricao: 'Projeto pessoal para uma associação de futebol de mesa.', tipo: tipos[0], linguagem: linguagens[3], url: 'http://lucfm.000webhostapp.com/', modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[3]}`, repositorio: ' '},
   { titulo: 'Gestão de Super Mercado', descricao: 'Projeto criado para gestão de supermercado.', tipo: tipos[0], linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/sites/supermercado/bancodedados/view/', modelo: modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[3]}`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/supermercado'}, */
   { titulo: 'Lista de Tarefas', descricao: 'Projeto criando um modelo de lista de tarefas.', linguagem: linguagens[5], url: 'https://lista-tarefas-flame.vercel.app/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[5]}`, repositorio: 'https://github.com/clovisbalreira/react_js/tree/main/lista_tarefas'},    
   { titulo: 'Sistema Financeiro', descricao: 'Projeto criando um modelo de lista de financeiro.', linguagem: linguagens[5], url: 'https://sistema-financeiro-gold.vercel.app/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[5]}`, repositorio: 'https://github.com/clovisbalreira/react_js/tree/main/sistema_financeiro'},    
   { titulo: 'Galeria', descricao: 'Projeto criando um modelo de galeria de fotos', linguagem: linguagens[5], url: 'https://galeria-three.vercel.app/', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[5]}`, repositorio: 'https://github.com/clovisbalreira/react_js/tree/main/galeria'},
   { titulo: 'Pesquisar e avaliar', descricao: 'Projeto pessoal para pesquisar e avaliar o que os deputados estão fazendo no congresso. Com api externa.', linguagem: linguagens[5], url: 'https://private-neon.vercel.app/', tipo: tipos[0], modelo:  modelos[0], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[5]}`, repositorio: 'https://private-neon.vercel.app/'},    
   { titulo: 'Estruturado', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/Estruturado', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/Estruturado'},    
   { titulo: 'Funcionario privado', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/FuncionarioPrivate', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/FuncionarioPrivate'},    
   { titulo: 'Pessoa', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/Pessoa', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/Pessoa'},    
   { titulo: 'Exercicio', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/exercicios', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/exercicios'},    
   { titulo: 'Funcionario', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/funcionario', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/funcionario'},    
   { titulo: 'Locadora', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/locadora', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/locadora'},    
   { titulo: 'Projeto', descricao: 'Projeto java.', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/projeto', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/projeto'},    
   { titulo: 'Desafio wp', descricao: 'Projeto criado no modelo do desafio desafio wp. Criação de tema', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/desafio-wp', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[3], tag: `${tags} ${tagsLinguagem[7]}`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/desafio-wp'},
   { titulo: 'Rádio C.N.S.', descricao: 'Radio C.N.S. - Canoas', linguagem: linguagens[7], url: 'https://radiocns.com/', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[7]}`, repositorio: 'https://radiocns.com/'},    
   { titulo: 'Rádio modelo 001', descricao: 'Projeto pessoal para rádio - usando plugins ( v . 1 ).', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[7]}`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns'},    
   { titulo: 'Rádio modelo 002', descricao: 'Projeto pessoal para rádio - usando plugins ( v . 2 ).', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns%20v2.0', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[7]}`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns%20v2.0'},    
   { titulo: 'Rádio modelo 003', descricao: 'Projeto pessoal para rádio - usando plugins ( v . 3 ).', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns%20v3.0', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[7]}`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/Cns%20v3.0'},
    { titulo: 'Cartao Flutter', descricao: 'Projeto de cartões. Com api externa.', linguagem: linguagens[8], url: 'https://github.com/clovisbalreira/flutter/tree/main/cartaoFlutter', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/flutter/tree/main/cartaoFlutter'},   
    { titulo: 'Pokemon', descricao: 'Projeto de cartões. Com api externa.', linguagem: linguagens[8], url: 'https://github.com/clovisbalreira/flutter/tree/main/Pokemon', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[0], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/flutter/tree/main/Pokemon'},    
    { titulo: 'App Filmes', descricao: 'Projeto de cartões. Com api externa.', linguagem: linguagens[8], url: 'https://github.com/clovisbalreira/flutter/tree/main/app_filmes', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/flutter/tree/main/app_filmes'},     
    { titulo: 'Aluno', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Aluno', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Aluno'},    
    { titulo: 'Aluno Conceito', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/AlunoConceito', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/AlunoConceito'},    
    { titulo: 'Associação', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Associacao', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Associacao'},    
    { titulo: 'Banco dados', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/BancoDados', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/BancoDados'},    
    { titulo: 'Comissão', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Comissao', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Comissao'},    
    { titulo: 'Data', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Data', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Data'},    
    { titulo: 'Nadador', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Nadador', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Nadador'},    
    { titulo: 'Pessoa peso', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/PessoaPeso', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/PessoaPeso'},    
    { titulo: 'Projeto soma', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/ProjASoma', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/ProjASoma'},    
    { titulo: 'Renda familia', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/RendaFamilia', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/RendaFamilia'},    
    { titulo: 'Saque', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Saque', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Saque'},    
    { titulo: 'Signos', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Signos', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Signos'},    
    { titulo: 'Triangulo', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Triangulo', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/Triangulo'},    
    { titulo: 'Projeto Operações', descricao: 'Projeto Android', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/pessoal/projAOperacoes', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/pessoal/projAOperacoes'},    
    { titulo: 'Aluno', descricao: 'Projeto Kotlin', linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Aluno', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]}`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Aluno'},    
    { titulo: 'Funcionario', descricao: 'Projeto Kotlin', linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Funcionario', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]}`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Funcionario'},    
    { titulo: 'Produto', descricao: 'Projeto Kotlin', linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Produto', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]}`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/Produto'},    
    { titulo: 'Soma', descricao: 'Projeto Kotlin', linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/soma', tipo: tipos[1], modelo: modelos[3], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]}`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/pessoal/soma'},    
    { titulo: 'Designer', descricao: 'Projetos gráficos.', linguagem: linguagens[linguagens.length - 1], url: 'sites/imagens/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[0], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/imagens'},
    
    //Curso em video - html - css
    { titulo: 'Curso em video', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[0], url: './sites/curso-em-video-html-css/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css'},
    {titulo: 'Curiosidades de Tecnologia', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[0], url: 'sites/curso-em-video-html-css/desafios/d010/', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[0]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css/desafios/d010'},
    {titulo: 'Cordel Moderno', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[0], url: './sites/curso-em-video-html-css/desafios/d012/', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[0]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css/desafios/d012'},
    {titulo: 'Projeto Redes Socias', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[0], url: './sites/curso-em-video-html-css/desafios/d015/', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[0]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css/desafios/d015'},
    {titulo: 'Login', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[0], url: './sites/curso-em-video-html-css/desafios/d016/', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[0]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css/desafios/d016'},
    
    //Curso em video - html - css - javascript
    {titulo: 'Curso em vídeo', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[1], url: './sites/curso-em-video-html-css-javascript/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #cursoemvideo #gustavoguanabara`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css-javascript'},
    { titulo: 'Acender Lambada', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-html-css-javascript/lambada/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-html-css-javascript/lambada'},
    { titulo: 'Curso em video - JavaScript', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript'},    
    { titulo: 'Muda a imagem na dependendo a hora', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript/ex011', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript/ex011'},    
    { titulo: 'Mostra uma imagem dependendo do ano e genero', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript/ex012', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript/ex012'},    
    { titulo: 'Vamos contar', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript/ex014', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript/ex014'},    
    { titulo: 'Tabuada', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript/ex015', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript/ex015'},    
    { titulo: 'Analisador de numeros', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[2], url: './sites/curso-em-video-javascript/ex018', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[2]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-javascript/ex018'},    
    //Curso em video - PHP
    { titulo: 'P.H.P. ( Básico curso em vídeo )', descricao: 'Projeto criado no modelo do P.H.P. ( Básico curso em vídeo ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/sites/basico/', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[3]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/basico'},
    { titulo: 'P.H.P. ( P.O.O. curso em vídeo )', descricao: 'Projeto criado no modelo do P.H.P. ( P.O.O. curso em vídeo ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/sites/poo/index.php', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[3]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/poo'},
    { titulo: 'Estudonauta', descricao: 'Projeto criado no modelo do estudonauta. Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/sites/estudonauta/index.php', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[3]} #estudonauta`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/estudonauta'},
    //Curso em video - MySql
    { titulo: 'MySql ( Básico curso em vídeo )', descricao: 'Projeto criado no modelo do MySql ( Básico curso em vídeo ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[4], url: 'https://php-projetos-clovis.000webhostapp.com/sites/mysql/index.php', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[4]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/mysql'},
    //Curso em video - Java
    { titulo: 'Curso em video', descricao: 'Exercicios de java básico', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/curso_em_video_java_basico', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/curso_em_video_java_basico'},    
    { titulo: 'Curso em video java poo', descricao: 'Exercicios de java POO', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/curso_em_video_java_poo', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/curso_em_video_java_poo'},    
    //Curso em video - WordPress
    { titulo: 'Modelo curso em video - pizzaria fresco', descricao: 'Projeto criado no modelo do curso em vídeo - usando plugins. Com mentoria de Gustavo Guanabara Ramiro Lobo.', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/CursoEmVideo', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos
    //Curso em video - Android
    [2], tag: `${tags} ${tagsLinguagem[7]} #cursoemvideo #gustavoguanabara  #estudonauta`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/CursoEmVideo'},
    { titulo: 'Escola  ( Estudonauta )', descricao: 'Projeto criado no modelo do Android ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/Escola', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/Escola'},
    { titulo: 'Olá mundo 20 ( Estudonauta )', descricao: 'Projeto criado no modelo do Android ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/OlaMundo20', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/OlaMundo20'},
    { titulo: 'Estudonauta ( Estudonauta )', descricao: 'Projeto criado no modelo do Android ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/estudonauta', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/estudonauta'},
    { titulo: 'Olá mundo ( Estudonauta )', descricao: 'Projeto criado no modelo do Android ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/olamundo', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/olamundo'},
    { titulo: 'Meu Nome ( Estudonauta )', descricao: 'Projeto criado no modelo do Android ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/MeuNome', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/estudonauta/MeuNome'},
    //Curso em video - Kotlin
    { titulo: 'Olá Mundo ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/000_Ola_Mundo', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/000_Ola_Mundo'},
    { titulo: 'Mostrar Cisas na tela( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/001_Mostrar_Coisas_Tela', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/001_Mostrar_Coisas_Tela'},
    { titulo: 'Comentarios ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/002_Comentarios', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/002_Comentarios'},
    { titulo: 'Tipos primitivos ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/003_Tipos_Primitivos', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/003_Tipos_Primitivos'},
    { titulo: 'Variaveis ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/004_Variaveis', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/004_Variaveis'},
    { titulo: 'Variaveis constantes ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/005_VariaveisConstantes', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/005_VariaveisConstantes'},
    { titulo: 'Conversor tipos ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/006_Conversor_Tipos', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/006_Conversor_Tipos'},
    { titulo: 'Analisando tipos ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/007_Analisando_Tipos', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/007_Analisando_Tipos'},
    { titulo: 'Valor nulo ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/008_Valor_Nulo', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/008_Valor_Nulo'},
    { titulo: 'Saidas interpoladas ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/009_Saidas_Interpoladas', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/009_Saidas_Interpoladas'},
    { titulo: 'Cores ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/010_Cores', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/010_Cores'},
    { titulo: 'Entrada dados ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/011_Entrada_Dados', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/011_Entrada_Dados'},
    { titulo: 'Entrada validando ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/012_Entrada_Validando', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/012_Entrada_Validando'},
    { titulo: 'Operadores aritmeticos ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/013_Operatores_Aritmeticos', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/013_Operatores_Aritmeticos'},
    { titulo: 'Biblioteca ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/014_Biblioteca', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/014_Biblioteca'},
    { titulo: 'Operatores relacionais ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/015_Operatores_relacionais', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/015_Operatores_relacionais'},
    { titulo: 'Operatores atribuição ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/016_Operatores_Atribuicao', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/016_Operatores_Atribuicao'},
    { titulo: 'Operatores incremento decremento ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/017_Operatores_Incremento_Decremento', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/017_Operatores_Incremento_Decremento'},
    { titulo: 'Operatores logicos ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/018_Operatores_Logicos', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/018_Operatores_Logicos'},
    { titulo: 'Valores aleatorios ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/019_Valores_Aleatorios', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/019_Valores_Aleatorios'},
    { titulo: 'Data hora ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/020_Data_Hora', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/020_Data_Hora'},
    { titulo: 'Exercicios ( Estudonauta )', descricao: 'Projeto criado no modelo do Kotlin ( Estudonauta ). Com mentoria de Gustavo Guanabara.', tipo: tipos[0], linguagem: linguagens[12], url: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/021_Exercicios', modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[12]} #cursoemvideo #gustavoguanabara #estudonauta`, repositorio: 'https://github.com/clovisbalreira/kotlin/tree/main/estudonauta/021_Exercicios'},
    //Curso em video - Kotlin
    {titulo: 'Curso em vídeo - python', descricao: 'Projeto criado no modelo do curso em vídeo. Com mentoria de Gustavo Guanabara.', linguagem: linguagens[9], url: './sites/curso-em-video-python/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #cursoemvideo #gustavoguanabara`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/curso-em-video-python'},

    //onebitcode
    {titulo: 'Onebitcode', descricao: 'Projeto criado no modelo do Onebitcode.', linguagem: linguagens[1], url: './sites/onebitcode', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/onebitcode'},
    
    //Sujeito Programador
    {titulo: 'Sujeito Programador', descricao: 'Projeto criado no modelo do Sujeito Programador.', linguagem: linguagens[1], url: './sites/sujeitoprogramador', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/sujeitoprogramador'},

    //Dev Dobro
    {titulo: 'Dev Dobro', descricao: 'Projeto criado no modelo do Dev Dobro. Com mentoria com os Kadu e Beto.', linguagem: linguagens[1], url: './sites/devdobro', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/devdobro'},
    {titulo: 'Dev Dobro - Mario', descricao: 'Projeto criado no modelo do Dev Dobro. Com mentoria com os Kadu e Beto.', linguagem: linguagens[1], url: './sites/devdobro/desafio01', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/devdobro/desafio01'},
    {titulo: 'Dev Dobro - The last of us', descricao: 'Projeto criado no modelo do Dev Dobro. Com mentoria com os Kadu e Beto.', linguagem: linguagens[1], url: './sites/devdobro/desafio02', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/devdobro/desafio02'},
    {titulo: 'Dev Dobro - Pokemon', descricao: 'Projeto criado no modelo do Dev Dobro. Com mentoria com os Kadu e Beto.', linguagem: linguagens[1], url: './sites/devdobro/desafio03', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/devdobro/desafio03'},
    {titulo: 'Dev Dobro - X-men', descricao: 'Projeto criado no modelo do Dev Dobro. Com mentoria com os Kadu e Beto.', linguagem: linguagens[1], url: './sites/devdobro/desafio04', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/devdobro/desafio04'},
    
    // Rocketseat
    {titulo: 'Grid - Player de música', descricao: 'Projeto criado no modelo de player-rocketseat. Com mentoria de Mayk Brito', linguagem: linguagens[0], url: 'sites/player-rocketseat/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/player-rocketseat'},
    {titulo: 'Grid - Rocketseat', descricao: 'Projeto criado no modelo de Grid- Rocketseat. Com mentoria de Mayk Brito', linguagem: linguagens[0], url: 'sites/grid-rocketseat/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/grid-rocketseat'},
    {titulo: 'BoraCodar - Jornada do zero a primeira vaga ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/jornada-do-zero-a-primeira-vaga/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/jornada-do-zero-a-primeira-vaga'},
    {titulo: 'BoraCodar', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar'},
    {titulo: 'BoraCodar - Player de música', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio01/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio01'},
    {titulo: 'BoraCodar - Produto cartão', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio02/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio02'},
    {titulo: 'BoraCodar - Botões e Cursores', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio03/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio03'},
    {titulo: 'BoraCodar - Chat', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio04/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio04'},
    {titulo: 'BoraCodar - Calculadora', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio05/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio05'},
    {titulo: 'BoraCodar - Cartão de embarque', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio06/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio06'},
    {titulo: 'BoraCodar - Encontre seu bloco de carnaval', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio07/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio07'},
    {titulo: 'BoraCodar - Dashboard ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio08/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio08'},
    {titulo: 'BoraCodar - Conversão de moeda ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio09/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio09'},
    {titulo: 'BoraCodar - Clima ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio10/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio10'},
    {titulo: 'BoraCodar - Login ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio11/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio11'},
    {titulo: 'BoraCodar - Kanban ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio12/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio12'},
    {titulo: 'BoraCodar - Formulário de cartão de crédito ', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio13/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio13'},
    {titulo: 'BoraCodar - Upload', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio14/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio14'},
    {titulo: 'BoraCodar - Tabela de Preços', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio15/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio15'},
    {titulo: 'BoraCodar - Scrollbar', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio16/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio16'},
    {titulo: 'BoraCodar - Data', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio17/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio17'},
    {titulo: 'BoraCodar - Efeito 3D', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio18/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio18'},
    {titulo: 'BoraCodar - Interface UBER', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio19/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio19'},
    {titulo: 'BoraCodar - Galeria', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio20/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio20'},
    {titulo: 'BoraCodar - Carrinho de compras', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio21/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio21'},
    {titulo: 'BoraCodar - Profile Settings', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio22/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio22'},
    {titulo: 'BoraCodar - Formulário', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio23/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio23'},
    {titulo: 'BoraCodar - Ajustes de iluminação', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio24/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio24'},
    {titulo: 'BoraCodar - Interações em VR', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio25/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio25'},
    {titulo: 'BoraCodar - Receitas', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio26/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio26'},
    {titulo: 'BoraCodar - Página de erro', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio27/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio27'},
    {titulo: 'BoraCodar - Plataforma de IA', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio28/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio28'},
    {titulo: 'BoraCodar - Antes e depois da IA', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio29/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio29'},
    {titulo: 'BoraCodar - Sujestão de filmes', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio30/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio30'},
    // node JS
    /* {titulo: 'BoraCodar - Transcrição de vídeo com IA', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[5], url: './sites/boracodar/desafio31/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio31'}, */
    // Next
    /* {titulo: 'BoraCodar - SQL com IA', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[5], url: './sites/boracodar/desafio32/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio32'}, */
    {titulo: 'BoraCodar - Ticket IA', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio33/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio33'},
    {titulo: 'BoraCodar - Select Customizado', descricao: 'Projeto criado no modelo do boracodar. Com mentoria de Mayk Brito e Biro.', linguagem: linguagens[1], url: './sites/boracodar/desafio34/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #boracodar #maykbrito`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/boracodar/desafio34'},
    
    //alura
    {titulo: 'Alura - Barbearia', descricao: 'Projeto criado no modelo da alura.', linguagem: linguagens[1], url: 'sites/alura/barbearia/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tagsLinguagem[0]} ${tags} #alura `, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura/barbearia/'},
    {titulo: 'Alura - Biografia', descricao: 'Projeto criado no modelo da alura.', linguagem: linguagens[1], url: 'sites/alura/biografia/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tagsLinguagem[0]} ${tags} #alura `, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura/biografia/'},


    // Alura imersão
    {titulo: 'Imersão Dev - Alura', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tagsLinguagem[0]} ${tags} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini #7DaysOfCode`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/'},
    { titulo: 'Alura - Conversor de moedas v 1.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/conversor-moeda/conversor.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/conversor-moeda'},
    { titulo: 'Alura - Conversor de moedas v 2.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/conversor-moeda/conversorv2.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/conversor-moeda'},
    { titulo: 'Alura - Aluraflix 1.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/alura-flix/alura_flix.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/alura-flix'},
    { titulo: 'Alura - Aluraflix 2.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/alura-flix/alura_flixv2.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/alura-flix'},
    { titulo: 'Alura - Tabela v 1.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/tabela/tabela.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/tabela/tabela.html'},
    { titulo: 'Alura - Tabela v 2.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/tabela/tabelav2.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/tabela/tabela.html'},
    { titulo: 'Alura - Super Trunfo', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/super-trunfo/super_trunfo.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/super-trunfo'},
    { titulo: 'Alura - Mentalista v 1.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/mentalista/mentalista.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/mentalista'},
    { titulo: 'Alura - Mentalista v 2.0', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/mentalista/mentalistav2.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/mentalista'},
    {titulo: 'Alura - Calculadora de Média', descricao: 'Projeto criado no modelo da imersão da alura. Com mentoria de paulo Silveira, Rafaella Ballerini e Guilherme Lima.', linguagem: linguagens[1], url: 'sites/alura-imersao/calculadora-media/calculadora_media.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[0]} #alura #ImersãoDev #rafaellaballerini #paulosilveira #guilhermelima #comunidaderafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/calculadora-media'},
    { titulo: 'JavaScript - #7DaysOfCode - 1º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia01.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 2º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia02.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 3º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia03.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 4º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia04.html', tipo: tipos[0], modelo: modelos[1], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 5º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia05.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 6º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia06.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'JavaScript - #7DaysOfCode - 7º dia', descricao: 'Projeto do desafio #7DaysOfCode', linguagem: linguagens[2], url: 'sites/alura-imersao/desafios-alura/dia07.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/alura-imersao/desafios-alura/'},
    { titulo: 'Landing Page', descricao: 'Projeto criado no modelo Landing page. Com mentoria de Rafaella Balerine.', linguagem: linguagens[0], url: 'sites/landingpage/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[1], tag: `${tags} ${tagsLinguagem[1]} #rafaellaballerini`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/landingpage'},
    
    /*  
    { titulo: 'Imersão React Alura - AluraCord - Matrix Cord', descricao: 'Projeto criado no modelo da imersão alura react. criando uma chat.', linguagem: linguagens[5],  url: 'https://aluracord-matrixchat.vercel.app/', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[5]} #alura #ImersãoDev`, repositorio: ' '},    
    */

   // wordPress
   { titulo: 'Tema Malura', descricao: 'Projeto criado no modelo da alura - criação de tema', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/malura', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[7]} #alura`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/malura'},    
   { titulo: 'Tema Intercambios', descricao: 'Projeto criado no modelo da alura - criação de tema', linguagem: linguagens[7], url: 'https://github.com/clovisbalreira/wordpress/tree/main/alura-intercambios', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[7]} #alura`, repositorio: 'https://github.com/clovisbalreira/wordpress/tree/main/alura-intercambios'},    
   { titulo: 'Alura', descricao: 'Projeto criado java da alura - criação de tema', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/alura', tipo: tipos[2], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]} #alura`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/alura'},    
   
   //Neri Netzke
   {titulo: 'Neri Netzke', descricao: 'Projeto criado no modelo da informaticon com exemplos de tags. Com mentoria de Neri Netzke.', linguagem: linguagens[1], url: 'sites/neri-neitzke/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Nao', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #informaticon #nerineitzke`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/neri-neitzke'},
   /* { titulo: 'Informaticon', descricao: 'Projeto criado no modelo da informaticon. Com mentoria de Neri Neitzke.', linguagem: linguagens[3], url: 'https://php-projetos-clovis.000webhostapp.com/sites/carrinho/index.php', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[3]}`, repositorio: 'https://github.com/clovisbalreira/php/tree/main/sites/carrinho'}, */    
    { titulo: 'Acender Led ( Informaticon )', descricao: 'Projeto da informaticon. Com mentoria de Neri Neitzke.', linguagem: linguagens[10], url: 'https://github.com/clovisbalreira/arduino/tree/main/neriArduino', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[10]}`, repositorio: 'https://github.com/clovisbalreira/arduino/tree/main/neriArduino'},    
  
  // Deitel
  { titulo: 'Gorjeta ( Deitel )', descricao: 'Projeto do livro deitel.', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/deitel/Gorjeta', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/deitel/Gorjeta'},    
  { titulo: 'Favorite Twitter Searches ( Deitel )', descricao: 'Projeto do livro deitel.', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/deitel/favoriteTwitterSearches', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/deitel/favoriteTwitterSearches'},    
  { titulo: 'Welcome ( Deitel )', descricao: 'Projeto do livro deitel.', linguagem: linguagens[11], url: 'https://github.com/clovisbalreira/android/tree/main/deitel/welcome', tipo: tipos[0], modelo: modelos[0], status: 'Não', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[11]}`, repositorio: 'https://github.com/clovisbalreira/android/tree/main/deitel/welcome'},    
  
  
  // Dio
  {titulo: 'Multiverso Spider Man', descricao: 'Projeto criado no modelo da Dio. Com mentoria de Michele Ambrosio e Diogo M Mainardes.', linguagem: linguagens[1], url: 'sites/multiverso-spiderman/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags} #dio #digitalinnovationone`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/multiverso-spiderman'},
  { titulo: 'Bootstrap', descricao: 'Projeto criado no modelo com o framework bootstrap.', linguagem: linguagens[0], url: 'sites/bootstrap/', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[1]} #bootstrap`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/bootstrap'},
  { titulo: 'Projeto Dio', descricao: 'Projeto criado no modelo da projeto dio.', linguagem: linguagens[0], url: 'sites/projeto-dio/index.html', tipo: tipos[0], modelo: modelos[2], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[1]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/projeto-dio'},    
  { titulo: 'Java ( Digital Innovation )', descricao: 'Exercicios de java básico', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/curso_dio_java', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/curso_dio_java'},    
  { titulo: 'Java banco de dados ( Digital Innovation )', descricao: 'Exercicios de java com banco de dados', linguagem: linguagens[6], url: 'https://github.com/clovisbalreira/java/tree/main/curso_dio_java_banco_de_dados', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[6]}`, repositorio: 'https://github.com/clovisbalreira/java/tree/main/curso_dio_java_banco_de_dadoscurso_dio_java'},    
  { titulo: 'Python ( Digital Innovation )', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/curso_dio_python', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/imagens'},
  
  // celke
  { titulo: 'Celke', descricao: 'Javascript e criando estrutura', linguagem: linguagens[2], url: 'sites/celke/index.html', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[3], tag: `${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/celke'},
  
  // Hashtag
  { titulo: 'Hashtag - E-commerce', descricao: 'Projeto criado no modelo do hashtag. Com mentoria de Daniel', linguagem: linguagens[13], url: 'https://github.com/clovisbalreira/vite/tree/main/e-commerce', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[5]}`, repositorio: 'https://github.com/clovisbalreira/vite/tree/main/e-commerce'},    
  {titulo: 'Hashtag - E-commerce', descricao: 'Projeto criado no modelo do hashtag. Com mentoria de Daniel.', linguagem: linguagens[1], url: './sites/e-commerce/', tipo: tipos[0], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[1]} ${tags} #daniel`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/e-commerce'},
  {titulo: 'Hashtag - Javascript', descricao: 'Projeto criado no modelo do hashtag. Com mentoria de Daniel', linguagem: linguagens[0], url: 'sites/hashtag-javascript/index.html', tipo: tipos[1], modelo: modelos[0], status: 'Sim', projeto: projetos[2], tag: `${tagsLinguagem[0]} ${tags}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/sites/hashtag-javascript'},
  { titulo: 'Python - Hashtag - Criar pdf', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/criar-pdf', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/criar-pdf'},
  { titulo: 'Python - Hashtag - Minicurso Hashtag', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/minicurso-hashtag', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/minicurso-hashtag'},
  /* { titulo: 'Python - Hashtag - Minicurso Hashtag Ciencia de dados', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/minicurso-hashtag-ciencia-de-dados', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/minicurso-hashtag-ciencia-de-dados'}, */
  { titulo: 'Python - Hashtag - Organizar Arquivos', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/organizar-arquivos', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/organizar-arquivos'},
  { titulo: 'Python - Hashtag - Python Dev', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/python-dev', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/python-dev'},
  { titulo: 'Python - Hashtag - Python IA', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/python-ia', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/python-ia'},
  { titulo: 'Python - Hashtag - Python Insights', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/python-insights', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/python-insights'},
  { titulo: 'Python - Hashtag - Python Powerup', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/python-powerup', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/python-powerup'},
  /* { titulo: 'Python - Hashtag - Site Django', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/site-django', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/site-django'}, */
  { titulo: 'Python - Hashtag - Site Flask', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/site_flask', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/site_flask'},
 
  // varos
  /* { titulo: 'Python - Varos - Investimento', descricao: 'Exercicios de python básico', linguagem: linguagens[9], url: 'https://github.com/clovisbalreira/python/tree/main/investimento', tipo: tipos[1], modelo: modelos[3], status: 'Sim', projeto: projetos[2], tag: `${tags} ${tagsLinguagem[8]}`, repositorio: 'https://github.com/clovisbalreira/portfolio/tree/main/investimento'}, */
]