import { Conta } from "../model/Conta.js";
import { tipoContas } from "./tipoContas.js";

export let contas = [    
    new Conta(tipoContas[0], 'Fonte de Renda 1 ( Liquido )', 0, 0, '', false, 0),
    new Conta(tipoContas[0], 'Fonte de Renda 2 ( Liquido )', 0, 0, '', false, 0),
    new Conta(tipoContas[1], '13º Salário liquido', 0, 0, '', false, 0),
    new Conta(tipoContas[1], 'Férias', 0, 0, '', false, 0),
    new Conta(tipoContas[1], 'Bônus e extras', 0, 0, '', false, 0),
    new Conta(tipoContas[2], 'Metizinha ( um jantar, um sapato, uma blusinha - 3 meses )', 0, 0, '', false, 0),
    new Conta(tipoContas[2], 'Metinha ( Reserva emergência - 6 meses )', 0, 0, '', false, 0),
    new Conta(tipoContas[2], 'Meta ( Viagem internacional - 1 ano )', 0, 0, '', false, 0),
    new Conta(tipoContas[2], 'Metona ( Casa própria - 10 anos )', 0, 0, '', false, 0),
    new Conta(tipoContas[2], 'Metozona ( Aposentadoria - 30 anos )', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Aluguel', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Condomínio', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'IPTU', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Conta de água', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Conta de energia', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Seguro residencial', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Conta de gás', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Celular + TV + Internet', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Celular', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Streaming', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Supermercado', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Feira', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Pets', 0, 0, '', false, 0),
    new Conta(tipoContas[3], 'Faxineira', 0, 0, '', false, 0),
    new Conta(tipoContas[4], 'Financiamento', 0, 0, '', false, 0),
    new Conta(tipoContas[4], 'Cheque especial', 0, 0, '', false, 0),
    new Conta(tipoContas[4], 'Empréstimo consignado', 0, 0, '', false, 0),
    new Conta(tipoContas[4], 'Cartão de crédito atrasado', 0, 0, '', false, 0),
    new Conta(tipoContas[4], 'Tributos atrasados', 0, 0, '', false, 0),
    new Conta(tipoContas[5], 'Plano de saúde', 0, 0, '', false, 0),
    new Conta(tipoContas[5], 'Médicos e terapeutas', 0, 0, '', false, 0),
    new Conta(tipoContas[5], 'Dentista', 0, 0, '', false, 0),
    new Conta(tipoContas[5], 'Farmácia', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Licenciamento + multas', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'IPVA + Seguro Obrigatório', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'IPVA + Seguro', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Combustivel', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Estacionamentos', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Lavagens', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Mecânico / Revisão', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Multas', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Pedágios + Tag', 0, 0, '', false, 0),
    new Conta(tipoContas[6], 'Taxi ou APP', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Pós Graduação', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Material escolar', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Higiene pessoal ( unhas, depilação etc. )', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Cosméticos', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Cabelereiro', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Vestuário', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Academia', 0, 0, '', false, 0),
    new Conta(tipoContas[7], 'Seguro de vida', 0, 0, '', false, 0),
    new Conta(tipoContas[8], 'Cursos extra curriculares', 0, 0, '', false, 0),
    new Conta(tipoContas[8], 'Livros', 0, 0, '', false, 0),
    new Conta(tipoContas[9], 'Restaurantes', 0, 0, '', false, 0),
    new Conta(tipoContas[9], 'Cafés, bares, e boates', 0, 0, '', false, 0),
    new Conta(tipoContas[9], 'Livraria, jornais e revistas', 0, 0, '', false, 0),
    new Conta(tipoContas[9], 'Spotify música e outros', 0, 0, '', false, 0),
    new Conta(tipoContas[9], 'Passeios', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Tarifas bancárias', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Ajuda aos país', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Gorjetas / caixinhas', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Doações e dizimos', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Extras diários', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Manutenção e reparos', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Médicos e terapeutas esporádicos', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Remédios', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Dedetização', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Presente de natal', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Presentes de mês', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Utilidades domésticas e decoração', 0, 0, '', false, 0),
    new Conta(tipoContas[10], 'Manutenção veiculo', 0, 0, '', false, 0),
]
