import { Campeoanato } from "../model/Campeoanato.js";

export const campeonatos = [
    new Campeoanato("Série A", [
        { colocacao : 'Campeão',  pontos: 800 },
        { colocacao : 'Vice',  pontos: 640 },
        { colocacao : '3',  pontos: 600 },
        { colocacao : '4',  pontos: 560 },
        { colocacao : '5',  pontos: 552 },
        { colocacao : '6',  pontos: 544 },
        { colocacao : '7',  pontos: 536 },
        { colocacao : '8',  pontos: 528 },
        { colocacao : '9',  pontos: 520 },
        { colocacao : '10',  pontos: 512 },
        { colocacao : '11',  pontos: 504 },
        { colocacao : '12',  pontos: 496 },
        { colocacao : '13',  pontos: 488 },
        { colocacao : '14',  pontos: 480 },
        { colocacao : '15',  pontos: 472 },
        { colocacao : '16',  pontos: 464 },
        { colocacao : '17',  pontos: 456 },
        { colocacao : '18',  pontos: 448 },
        { colocacao : '19',  pontos: 440 },
        { colocacao : '20',  pontos: 432 },
        { colocacao : '21',  pontos: 424 },
        { colocacao : '22',  pontos: 416 },
        { colocacao : '23',  pontos: 408 },
        { colocacao : '24',  pontos: 408 },
        { colocacao : '25',  pontos: 408 },
        { colocacao : '26',  pontos: 408 },
        { colocacao : '27',  pontos: 408 },
    ]),
    new Campeoanato("Série B", [
        { colocacao : 'Campeão',  pontos: 400 },
        { colocacao : 'Vice',  pontos: 320 },
        { colocacao : '3',  pontos: 300 },
        { colocacao : '4',  pontos: 280 },
        { colocacao : '5',  pontos: 276 },
        { colocacao : '6',  pontos: 272 },
        { colocacao : '7',  pontos: 268 },
        { colocacao : '8',  pontos: 264 },
        { colocacao : '9',  pontos: 260 },
        { colocacao : '10',  pontos: 256 },
        { colocacao : '11',  pontos: 252 },
        { colocacao : '12',  pontos: 248 },
        { colocacao : '13',  pontos: 244 },
        { colocacao : '14',  pontos: 240 },
        { colocacao : '15',  pontos: 236 },
        { colocacao : '16',  pontos: 232 },
        { colocacao : '17',  pontos: 228 },
        { colocacao : '18',  pontos: 224 },
        { colocacao : '19',  pontos: 220 },
        { colocacao : '20',  pontos: 216 },
        { colocacao : '21',  pontos: 212 },
        { colocacao : '22',  pontos: 208 },
        { colocacao : '23',  pontos: 204 },
        { colocacao : '24',  pontos: 204 },
        { colocacao : '25',  pontos: 204 },
        { colocacao : '26',  pontos: 204 },
        { colocacao : '27',  pontos: 204 },
    ]),
    new Campeoanato("Série C", [
        { colocacao : 'Campeão',  pontos: 200 },
        { colocacao : 'Vice',  pontos: 160 },
        { colocacao : 'Semifinal',  pontos: 150 },
        { colocacao : 'Quartas',  pontos: 140 },
        { colocacao : '3',  pontos: 150 },
        { colocacao : '4',  pontos: 140 },
        { colocacao : '5',  pontos: 138 },
        { colocacao : '6',  pontos: 136 },
        { colocacao : '7',  pontos: 134 },
        { colocacao : '8',  pontos: 132 },
        { colocacao : '9',  pontos: 130 },
        { colocacao : '10',  pontos: 128 },
        { colocacao : '11',  pontos: 126 },
        { colocacao : '12',  pontos: 124 },
        { colocacao : '13',  pontos: 122 },
        { colocacao : '14',  pontos: 120 },
        { colocacao : '15',  pontos: 118 },
        { colocacao : '16',  pontos: 116 },
        { colocacao : '17',  pontos: 114 },
        { colocacao : '18',  pontos: 112 },
        { colocacao : '19',  pontos: 110 },
        { colocacao : '20',  pontos: 108 },
        { colocacao : '21',  pontos: 106 },
        { colocacao : '22',  pontos: 104 },
        { colocacao : '23',  pontos: 102 },
        { colocacao : '24',  pontos: 102 },
        { colocacao : '25',  pontos: 102 },
        { colocacao : '26',  pontos: 102 },
        { colocacao : '27',  pontos: 102 },
    ]),
    new Campeoanato("Série D", [
        { colocacao : 'Campeão',  pontos: 100 },
        { colocacao : 'Vice',  pontos: 80 },
        { colocacao : 'Semifinal',  pontos: 75 },
        { colocacao : 'Quartas',  pontos: 70 },
        { colocacao : 'Oitavas',  pontos: 69 },
        { colocacao : '3ª fase',  pontos: 68 },
        { colocacao : '2ª fase',  pontos: 67 },
        { colocacao : '1ª fase',  pontos: 66 },
        { colocacao : '3',  pontos: 75 },
        { colocacao : '4',  pontos: 70 },
        { colocacao : '5',  pontos: 69 },
        { colocacao : '6',  pontos: 68 },
        { colocacao : '7',  pontos: 67 },
        { colocacao : '8',  pontos: 66 },
        { colocacao : '9',  pontos: 65 },
        { colocacao : '10',  pontos: 64 },
        { colocacao : '11',  pontos: 63 },
        { colocacao : '12',  pontos: 62 },
        { colocacao : '13',  pontos: 61 },
        { colocacao : '14',  pontos: 60 },
        { colocacao : '15',  pontos: 59 },
        { colocacao : '16',  pontos: 58 },
        { colocacao : '17',  pontos: 57 },
        { colocacao : '18',  pontos: 56 },
        { colocacao : '19',  pontos: 55 },
        { colocacao : '20',  pontos: 54 },
        { colocacao : '21',  pontos: 53 },
        { colocacao : '22',  pontos: 52 },
        { colocacao : '23',  pontos: 51 },
        { colocacao : '24',  pontos: 51 },
        { colocacao : '25',  pontos: 51 },
        { colocacao : '26',  pontos: 51 },
        { colocacao : '27',  pontos: 51 },
    ]),
    new Campeoanato("Copa do Brasil", [
        { colocacao : 'Campeão',  pontos: 600 },
        { colocacao : 'Vice',  pontos: 480 },
        { colocacao : 'Semifinal',  pontos: 450 },
        { colocacao : 'Quartas',  pontos: 400 },
        { colocacao : 'Oitavas',  pontos: 200 },
        { colocacao : '4ª fase',  pontos: 100 },
        { colocacao : '3ª fase',  pontos: 50 },
        { colocacao : '2ª fase',  pontos: 25 },
        { colocacao : '1ª fase',  pontos: 15 },
    ]),
]