let programacaoCns = new Programacao(dados[0])
programacaoCns.adicionarDia('Domingos')
programacaoCns.adicionarProgramas('Domingos','01:00','01:59','As Mais Pedidas')
programacaoCns.adicionarProgramas('Domingos','02:00','02:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Domingos','03:00','03:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Domingos','04:00','13:59','#CNS')
programacaoCns.adicionarProgramas('Domingos','14:00','14:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Domingos','15:00','15:59','#CNS')
programacaoCns.adicionarProgramas('Domingos','16:00','17:59','CNS Hits')
programacaoCns.adicionarProgramas('Domingos','18:00','18:59','As Mais Pedidas')
programacaoCns.adicionarProgramas('Domingos','19:00','20:59','Expresso do Rock')
programacaoCns.adicionarProgramas('Domingos','21:00','23:59','#CNS')
programacaoCns.adicionarDiaNumero('Domingos', '0')
programacaoCns.adicionarDia('Segunda à Sexta')
programacaoCns.adicionarProgramas('Segunda à Sexta','00:00','00:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Segunda à Sexta','01:00','02:59','CNS Hits')
programacaoCns.adicionarProgramas('Segunda à Sexta','03:00','05:59','Pop Rock CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','06:00','06:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Segunda à Sexta','07:00','07:59','Feedback CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','08:00','09:59','CNS Hits')
programacaoCns.adicionarProgramas('Segunda à Sexta','10:00','12:59','#CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','13:00','13:59','Pop Rock CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','14:00','15:59','#CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','16:00','17:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Segunda à Sexta','18:00','21:59','Feedback CNS')
programacaoCns.adicionarProgramas('Segunda à Sexta','22:00','22:59','DJ Star, com Mario D, (sextas)')
programacaoCns.adicionarProgramas('Segunda à Sexta','23:00','23:59','Pop Rock CNS')
programacaoCns.adicionarDiaNumero('Segunda à Sexta', '1')
programacaoCns.adicionarDiaNumero('Segunda à Sexta', '2')
programacaoCns.adicionarDiaNumero('Segunda à Sexta', '3')
programacaoCns.adicionarDiaNumero('Segunda à Sexta', '4')
programacaoCns.adicionarDiaNumero('Segunda à Sexta', '5')
programacaoCns.adicionarDia('Sábados')
programacaoCns.adicionarProgramas('Sábados','00:00','00:59','Uma Hora Direto')
programacaoCns.adicionarProgramas('Sábados','01:00','02:59','#CNS')
programacaoCns.adicionarProgramas('Sábados','03:00','04:59','CNS Hits')
programacaoCns.adicionarProgramas('Sábados','05:00','08:59','#CNS')
programacaoCns.adicionarProgramas('Sábados','09:00','09:59','As Mais Pedidas')
programacaoCns.adicionarProgramas('Sábados','10:00','11:59','#CNS')
programacaoCns.adicionarProgramas('Sábados','12:00','13:59','CNS Hits')
programacaoCns.adicionarProgramas('Sábados','14:00','14:59','DJ Star, com Mario D')
programacaoCns.adicionarProgramas('Sábados','15:00','16:59','As Mais Pedidas')
programacaoCns.adicionarProgramas('Sábados','16:00','19:59','#CNS')
programacaoCns.adicionarProgramas('Sábados','20:00','21:59','As Mais Pedidas')
programacaoCns.adicionarProgramas('Sábados','21:00','22:59','Pezão Show, com Sr Pezão')
programacaoCns.adicionarProgramas('Sábados','23:00','23:59','DJ Star, com Mario D')
programacaoCns.adicionarDiaNumero('Sábados', '6')
let programacaoMix = new Programacao(dados[1])
programacaoMix.adicionarDia('Domingos')
programacaoMix.adicionarProgramas('Domingos','00:00','11:59','Baú da Mix')
programacaoMix.adicionarProgramas('Domingos','12:00','12:59','Toca Pro Face')
programacaoMix.adicionarProgramas('Domingos','13:00','23:59','Baú da Mix')
programacaoMix.adicionarDiaNumero('Domingos', '0')
programacaoMix.adicionarDia('Segunda à Sexta')
programacaoMix.adicionarProgramas('Segunda à Sexta','00:00','11:59','Baú da Mix')
programacaoMix.adicionarProgramas('Segunda à Sexta','12:00','12:59','Toca Pro Face')
programacaoMix.adicionarProgramas('Segunda à Sexta','13:00','18:59','Baú da Mix')
programacaoMix.adicionarProgramas('Segunda à Sexta','19:00','19:59','Mix Tudo')
programacaoMix.adicionarProgramas('Segunda à Sexta','20:00','20:59','Agora o Bicho Vai Pegar')
programacaoMix.adicionarProgramas('Segunda à Sexta','21:00','23:59','Baú da Mix')
programacaoMix.adicionarDiaNumero('Segunda à Sexta', '1')
programacaoMix.adicionarDiaNumero('Segunda à Sexta', '2')
programacaoMix.adicionarDiaNumero('Segunda à Sexta', '3')
programacaoMix.adicionarDiaNumero('Segunda à Sexta', '4')
programacaoMix.adicionarDiaNumero('Segunda à Sexta', '5')
programacaoMix.adicionarDia('Sábados')
programacaoMix.adicionarProgramas('Sábados','00:00','11:59','Baú da Mix')
programacaoMix.adicionarProgramas('Sábados','12:00','12:59','Toca Pro Face')
programacaoMix.adicionarProgramas('Sábados','13:00','22:59','Baú da Mix')
programacaoMix.adicionarProgramas('Sábados','23:00','23:59','Club Mix')
programacaoMix.adicionarDiaNumero('Sábados', '6')
let programacao = [programacaoCns, programacaoMix]