import { Projeto } from '../model/Projeto.js'

export let projetos = [
  new Projeto( 2022, 'Projeto de Vídeos', 'Projeto construido para treinar a inserção de vídeos em nosso site.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-01-videos.jpg', '../d009/index.html'),
  new Projeto( 2023, 'Projeto Cordel', 'Projeto construido para treinar efeito paralax em imagens.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-02-cordel.jpg', '../d012/index.html'),
  new Projeto( 2022, 'Projeto Android', 'Projeto construido para treinar conteúdos e imagens dinâmicas.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-03-android.jpg', '../d010/index.html'),
  new Projeto( 2022, 'Projeto Links', 'Projeto construido para treinar tela de links.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-04-links.jpg', '../d015/index.html'),
  new Projeto( 2022, 'Projeto Login', 'Projeto construido para treinar tela de login.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-05-login.jpg', '../d016/index.html'),
  new Projeto( 2022, 'Projeto Album', 'Projeto construido para treinar album com imagens.', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi, blanditiis optio facilis incidunt sit nemo, mollitia labore nihil dolorum id ab in libero assumenda consequuntur quidem iusto deserunt! Itaque!', './imagens/projeto-06-album.jpg', '../d018/index.html'),
]