var jogos = [
    {fase:'grupo', rodada:1,jogo:1,hora:"08:00",mesa: 1,fotoCasa:jogadores[0].foto, timeCasa: jogadores[0].tecnico, golsCasa: 0,timeFora: jogadores[1].tecnico, fotoFora:jogadores[1].foto, golsFora: 0},
    {fase:'grupo', rodada:1,jogo:2,hora:"08:00",mesa: 2,fotoCasa:jogadores[2].foto, timeCasa: jogadores[2].tecnico, golsCasa: 1,timeFora: jogadores[3].tecnico, fotoFora:jogadores[3].foto, golsFora: 0},
    {fase:'grupo', rodada:1,jogo:3,hora:"08:00",mesa: 3,fotoCasa:jogadores[4].foto, timeCasa: jogadores[4].tecnico, golsCasa: 0,timeFora: jogadores[6].tecnico, fotoFora:jogadores[6].foto, golsFora: 1},
    {fase:'grupo', rodada:1,jogo:4,hora:"08:00",mesa: 4,fotoCasa:jogadores[7].foto, timeCasa: jogadores[7].tecnico, golsCasa: 1,timeFora: jogadores[5].tecnico, fotoFora:jogadores[5].foto, golsFora: 0},
    {fase:'grupo', rodada:1,jogo:5,hora:"08:00",mesa: 5,fotoCasa:jogadores[8].foto, timeCasa: jogadores[8].tecnico, golsCasa: 0,timeFora: jogadores[9].tecnico, fotoFora:jogadores[9].foto, golsFora: 3},
    {fase:'grupo', rodada:1,jogo:6,hora:"08:00",mesa: 6,fotoCasa:jogadores[10].foto, timeCasa: jogadores[10].tecnico, golsCasa: 1,timeFora: jogadores[11].tecnico, fotoFora:jogadores[11].foto, golsFora: 2},
    {fase:'grupo', rodada:1,jogo:7,hora:"08:00",mesa: 7,fotoCasa:jogadores[12].foto, timeCasa: jogadores[12].tecnico, golsCasa: 0,timeFora: jogadores[14].tecnico, fotoFora:jogadores[14].foto, golsFora: 3},
    {fase:'grupo', rodada:1,jogo:8,hora:"08:00",mesa: 8,fotoCasa:jogadores[15].foto, timeCasa: jogadores[15].tecnico, golsCasa: 0,timeFora: jogadores[13].tecnico, fotoFora:jogadores[13].foto, golsFora: 2},
    {fase:'grupo', rodada:1,jogo:9,hora:"08:00",mesa: 1,fotoCasa:jogadores[16].foto, timeCasa: jogadores[16].tecnico, golsCasa: 0,timeFora: jogadores[17].tecnico, fotoFora:jogadores[7].foto, golsFora: 4},
    {fase:'grupo', rodada:1,jogo:10,hora:"09:00",mesa: 2,fotoCasa:jogadores[18].foto, timeCasa: jogadores[18].tecnico, golsCasa: 1,timeFora: jogadores[19].tecnico, fotoFora:jogadores[19].foto, golsFora: 1},
    {fase:'grupo', rodada:1,jogo:11,hora:"09:00",mesa: 3,fotoCasa:jogadores[20].foto, timeCasa: jogadores[20].tecnico, golsCasa: 0,timeFora: jogadores[22].tecnico, fotoFora:jogadores[22].foto, golsFora: 4},
    {fase:'grupo', rodada:1,jogo:12,hora:"09:00",mesa: 4,fotoCasa:jogadores[23].foto, timeCasa: jogadores[23].tecnico, golsCasa: 1,timeFora: jogadores[21].tecnico, fotoFora:jogadores[21].foto, golsFora: 2},
    {fase:'grupo', rodada:1,jogo:13,hora:"09:00",mesa: 5,fotoCasa:jogadores[24].foto, timeCasa: jogadores[24].tecnico, golsCasa: 1,timeFora: jogadores[25].tecnico, fotoFora:jogadores[25].foto, golsFora: 1},
    {fase:'grupo', rodada:1,jogo:14,hora:"09:00",mesa: 6,fotoCasa:jogadores[26].foto, timeCasa: jogadores[26].tecnico, golsCasa: 0,timeFora: jogadores[27].tecnico, fotoFora:jogadores[27].foto, golsFora: 2},
    {fase:'grupo', rodada:1,jogo:15,hora:"09:00",mesa: 7,fotoCasa:jogadores[28].foto, timeCasa: jogadores[28].tecnico, golsCasa: 0,timeFora: jogadores[30].tecnico, fotoFora:jogadores[30].foto, golsFora: 1},
    {fase:'grupo', rodada:1,jogo:16,hora:"09:00",mesa: 8,fotoCasa:jogadores[31].foto, timeCasa: jogadores[31].tecnico, golsCasa: 2,timeFora: jogadores[29].tecnico, fotoFora:jogadores[29].foto, golsFora: 0},
    
    {fase:'grupo', rodada:2,jogo:17,hora:"10:00",mesa: 8,fotoCasa:jogadores[0].foto, timeCasa: jogadores[0].tecnico, golsCasa: 0,timeFora: jogadores[2].tecnico, fotoFora:jogadores[2].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:18,hora:"10:00",mesa: 7,fotoCasa:jogadores[1].foto, timeCasa: jogadores[1].tecnico, golsCasa: 5,timeFora: jogadores[3].tecnico, fotoFora:jogadores[3].foto, golsFora: 0},
    {fase:'grupo', rodada:2,jogo:19,hora:"10:00",mesa: 6,fotoCasa:jogadores[6].foto, timeCasa: jogadores[6].tecnico, golsCasa: 2,timeFora: jogadores[7].tecnico, fotoFora:jogadores[7].foto, golsFora: 0},
    {fase:'grupo', rodada:2,jogo:20,hora:"10:00",mesa: 5,fotoCasa:jogadores[5].foto, timeCasa: jogadores[5].tecnico, golsCasa: 1,timeFora: jogadores[4].tecnico, fotoFora:jogadores[4].foto, golsFora: 0},
    {fase:'grupo', rodada:2,jogo:21,hora:"10:00",mesa: 4,fotoCasa:jogadores[8].foto, timeCasa: jogadores[8].tecnico, golsCasa: 2,timeFora: jogadores[10].tecnico, fotoFora:jogadores[10].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:22,hora:"10:00",mesa: 3,fotoCasa:jogadores[9].foto, timeCasa: jogadores[9].tecnico, golsCasa: 2,timeFora: jogadores[11].tecnico, fotoFora:jogadores[11].foto, golsFora: 2},
    {fase:'grupo', rodada:2,jogo:23,hora:"10:00",mesa: 2,fotoCasa:jogadores[14].foto, timeCasa: jogadores[14].tecnico, golsCasa: 0,timeFora: jogadores[15].tecnico, fotoFora:jogadores[15].foto, golsFora: 3},
    {fase:'grupo', rodada:2,jogo:24,hora:"10:00",mesa: 1,fotoCasa:jogadores[13].foto, timeCasa: jogadores[13].tecnico, golsCasa: 3,timeFora: jogadores[12].tecnico, fotoFora:jogadores[12].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:25,hora:"11:00",mesa: 8,fotoCasa:jogadores[16].foto, timeCasa: jogadores[16].tecnico, golsCasa: 0,timeFora: jogadores[18].tecnico, fotoFora:jogadores[18].foto, golsFora: 0},
    {fase:'grupo', rodada:2,jogo:26,hora:"11:00",mesa: 7,fotoCasa:jogadores[17].foto, timeCasa: jogadores[17].tecnico, golsCasa: 3,timeFora: jogadores[19].tecnico, fotoFora:jogadores[19].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:27,hora:"11:00",mesa: 6,fotoCasa:jogadores[22].foto, timeCasa: jogadores[22].tecnico, golsCasa: 1,timeFora: jogadores[23].tecnico, fotoFora:jogadores[23].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:28,hora:"11:00",mesa: 5,fotoCasa:jogadores[21].foto, timeCasa: jogadores[21].tecnico, golsCasa: 4,timeFora: jogadores[20].tecnico, fotoFora:jogadores[20].foto, golsFora: 0},
    {fase:'grupo', rodada:2,jogo:29,hora:"11:00",mesa: 4,fotoCasa:jogadores[24].foto, timeCasa: jogadores[24].tecnico, golsCasa: 2,timeFora: jogadores[26].tecnico, fotoFora:jogadores[26].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:30,hora:"11:00",mesa: 3,fotoCasa:jogadores[25].foto, timeCasa: jogadores[25].tecnico, golsCasa: 0,timeFora: jogadores[27].tecnico, fotoFora:jogadores[27].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:31,hora:"11:00",mesa: 2,fotoCasa:jogadores[30].foto, timeCasa: jogadores[30].tecnico, golsCasa: 0,timeFora: jogadores[31].tecnico, fotoFora:jogadores[31].foto, golsFora: 1},
    {fase:'grupo', rodada:2,jogo:32,hora:"11:00",mesa: 1,fotoCasa:jogadores[29].foto, timeCasa: jogadores[29].tecnico, golsCasa: 2,timeFora: jogadores[28].tecnico, fotoFora:jogadores[28].foto, golsFora: 2},

    {fase:'grupo', rodada:3,jogo:33,hora:"12:00",mesa: 3,fotoCasa:jogadores[0].foto, timeCasa: jogadores[0].tecnico, golsCasa: 0,timeFora: jogadores[3].tecnico, fotoFora:jogadores[3].foto, golsFora: 3},
    {fase:'grupo', rodada:3,jogo:34,hora:"12:00",mesa: 4,fotoCasa:jogadores[2].foto, timeCasa: jogadores[2].tecnico, golsCasa: 0,timeFora: jogadores[1].tecnico, fotoFora:jogadores[1].foto, golsFora: 4},
    {fase:'grupo', rodada:3,jogo:35,hora:"12:00",mesa: 7,fotoCasa:jogadores[6].foto, timeCasa: jogadores[6].tecnico, golsCasa: 1,timeFora: jogadores[5].tecnico, fotoFora:jogadores[5].foto, golsFora: 1},
    {fase:'grupo', rodada:3,jogo:36,hora:"12:00",mesa: 8,fotoCasa:jogadores[7].foto, timeCasa: jogadores[7].tecnico, golsCasa: 0,timeFora: jogadores[4].tecnico, fotoFora:jogadores[4].foto, golsFora: 1},
    {fase:'grupo', rodada:3,jogo:37,hora:"12:00",mesa: 1,fotoCasa:jogadores[8].foto, timeCasa: jogadores[8].tecnico, golsCasa: 2,timeFora: jogadores[11].tecnico, fotoFora:jogadores[11].foto, golsFora: 3},
    {fase:'grupo', rodada:3,jogo:38,hora:"12:00",mesa: 2,fotoCasa:jogadores[10].foto, timeCasa: jogadores[10].tecnico, golsCasa: 0,timeFora: jogadores[9].tecnico, fotoFora:jogadores[9].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:39,hora:"12:00",mesa: 5,fotoCasa:jogadores[14].foto, timeCasa: jogadores[14].tecnico, golsCasa: 0,timeFora: jogadores[13].tecnico, fotoFora:jogadores[13].foto, golsFora: 1},
    {fase:'grupo', rodada:3,jogo:40,hora:"12:00",mesa: 6,fotoCasa:jogadores[15].foto, timeCasa: jogadores[15].tecnico, golsCasa: 1,timeFora: jogadores[12].tecnico, fotoFora:jogadores[12].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:41,hora:"13:00",mesa: 3,fotoCasa:jogadores[16].foto, timeCasa: jogadores[16].tecnico, golsCasa: 0,timeFora: jogadores[19].tecnico, fotoFora:jogadores[19].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:42,hora:"13:00",mesa: 4,fotoCasa:jogadores[18].foto, timeCasa: jogadores[18].tecnico, golsCasa: 0,timeFora: jogadores[17].tecnico, fotoFora:jogadores[17].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:43,hora:"13:00",mesa: 7,fotoCasa:jogadores[22].foto, timeCasa: jogadores[22].tecnico, golsCasa: 0,timeFora: jogadores[21].tecnico, fotoFora:jogadores[21].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:44,hora:"13:00",mesa: 8,fotoCasa:jogadores[23].foto, timeCasa: jogadores[23].tecnico, golsCasa: 0,timeFora: jogadores[20].tecnico, fotoFora:jogadores[20].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:45,hora:"13:00",mesa: 1,fotoCasa:jogadores[24].foto, timeCasa: jogadores[24].tecnico, golsCasa: 0,timeFora: jogadores[27].tecnico, fotoFora:jogadores[27].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:46,hora:"13:00",mesa: 2,fotoCasa:jogadores[26].foto, timeCasa: jogadores[26].tecnico, golsCasa: 0,timeFora: jogadores[25].tecnico, fotoFora:jogadores[25].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:47,hora:"13:00",mesa: 5,fotoCasa:jogadores[30].foto, timeCasa: jogadores[30].tecnico, golsCasa: 0,timeFora: jogadores[29].tecnico, fotoFora:jogadores[29].foto, golsFora: 0},
    {fase:'grupo', rodada:3,jogo:48,hora:"13:00",mesa: 6,fotoCasa:jogadores[31].foto, timeCasa: jogadores[31].tecnico, golsCasa: 0,timeFora: jogadores[28].tecnico, fotoFora:jogadores[28].foto, golsFora: 0},

    //quartas de Final
    {fase:'Quartas de Final', rodada:1,jogo:53,hora:'14:30',mesa: 1,fotoCasa:'', timeCasa:  '1º Grupo A', golsCasa: '0',timeFora: '1º Grupo E', fotoFora:'', golsFora: '0'},
    {fase:'Quartas de Final', rodada:2,jogo:54,hora:'14:30',mesa: 2,fotoCasa:'', timeCasa: '1º Grupo B', golsCasa: '',timeFora: '1º Grupo F', fotoFora:'', golsFora: ''},
    {fase:'Quartas de Final', rodada:3,jogo:55,hora:'14:30',mesa: 3,fotoCasa:'', timeCasa: '1º Grupo C', golsCasa: '',timeFora: '1º Grupo G', fotoFora:'', golsFora: ''},
    {fase:'Quartas de Final', rodada:4,jogo:56,hora:'14:30',mesa: 4,fotoCasa:'', timeCasa: '1º Grupo D', golsCasa: '',timeFora: '1º Grupo H', fotoFora:'', golsFora: ''},

    {fase:'Quartas de Final', rodada:5,jogo:49,hora:'14:30',mesa: 5,fotoCasa:'', timeCasa: '2º Grupo A', golsCasa: '',timeFora: '2º Grupo E', fotoFora:'', golsFora: ''},
    {fase:'Quartas de Final', rodada:6,jogo:50,hora:'14:30',mesa: 6,fotoCasa:'', timeCasa: '2º Grupo B', golsCasa: '',timeFora: '2º Grupo F', fotoFora:'', golsFora: ''},
    {fase:'Quartas de Final', rodada:7,jogo:51,hora:'14:30',mesa: 7,fotoCasa:'', timeCasa: '2º Grupo C', golsCasa: '',timeFora: '2º Grupo G', fotoFora:'', golsFora: ''},
    {fase:'Quartas de Final', rodada:8,jogo:52,hora:'14:30',mesa: 8,fotoCasa:'', timeCasa: '2º Grupo D', golsCasa: '',timeFora: '2º Grupo E', fotoFora:'', golsFora: ''},

    //semi final
    {fase:'Semi Final', rodada:1,jogo:57,hora:'15:30',mesa: 1,fotoCasa:'', timeCasa: 'Vencedor Jogo 1 ', golsCasa: '',timeFora: 'Vencedor Jogo 3 ', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:2,jogo:58,hora:'15:30',mesa: 2,fotoCasa:'', timeCasa: 'Vencedor Jogo 2 ', golsCasa: '',timeFora: 'Vencedor Jogo 4 ', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:3,jogo:59,hora:'15:30',mesa: 3,fotoCasa:'', timeCasa: 'Perdedor Jogo 1 ', golsCasa: '',timeFora: 'Perdedor Jogo 3 ', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:4,jogo:60,hora:'15:30',mesa: 4,fotoCasa:'', timeCasa: 'Perdedor Jogo 2 ', golsCasa: '',timeFora: 'Perdedor Jogo 4 ', fotoFora:'', golsFora: ''},

    {fase:'Semi Final', rodada:5,jogo:61,hora:'15:30',mesa: 5,fotoCasa:'', timeCasa: 'Vencedor Jogo 5', golsCasa: '',timeFora: 'Vencedor Jogo 7', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:6,jogo:62,hora:'15:30',mesa: 6,fotoCasa:'', timeCasa: 'Vencedor Jogo 6', golsCasa: '',timeFora: 'Vencedor Jogo 8', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:7,jogo:63,hora:'15:30',mesa: 7,fotoCasa:'', timeCasa: 'Perdedor Jogo 1', golsCasa: '',timeFora: 'Perdedor Jogo 3', fotoFora:'', golsFora: ''},
    {fase:'Semi Final', rodada:8,jogo:64,hora:'15:30',mesa: 8,fotoCasa:'', timeCasa: 'Perdedor Jogo 2', golsCasa: '',timeFora: 'Perdedor Jogo 4', fotoFora:'', golsFora: ''},

    //Final
    {fase:'Final', rodada:1,jogo:65,hora:'17:00',mesa: 1,fotoCasa:'', timeCasa: 'Vencedor Jogo 1', golsCasa: '',timeFora: 'Vencedor Jogo 2', fotoFora:'', golsFora: ''},
    {fase:'3ª Lugar', rodada:2,jogo:66,hora:'17:00',mesa: 2,fotoCasa:'', timeCasa: 'Perdedor Jogo 1', golsCasa: '',timeFora: 'Perdedor Jogo 2', fotoFora:'', golsFora: ''},
    {fase:'5ª Lugar', rodada:3,jogo:67,hora:'17:00',mesa: 3,fotoCasa:'', timeCasa: 'Vencedor Jogo 5', golsCasa: '',timeFora: 'Vencedor Jogo 6', fotoFora:'', golsFora: ''},
    {fase:'7ª Lugar', rodada:4,jogo:68,hora:'17:00',mesa: 4,fotoCasa:'', timeCasa: 'Perdedor Jogo 5', golsCasa: '',timeFora: 'Perdedor Jogo 6', fotoFora:'', golsFora: ''},

    {fase:'Final', rodada:5,jogo:69,hora:'17:00',mesa: 5,fotoCasa:'', timeCasa: 'Vencedor Jogo 5', golsCasa: '',timeFora: 'Vencedor Jogo 6', fotoFora:'', golsFora: ''},
    {fase:'3ª Lugar', rodada:6,jogo:70,hora:'17:00',mesa: 6,fotoCasa:'', timeCasa: 'Perdedor Jogo 3', golsCasa: '',timeFora: 'Perdedor Jogo 4', fotoFora:'', golsFora: ''},
    {fase:'5ª Lugar', rodada:7,jogo:71,hora:'17:00',mesa: 7,fotoCasa:'', timeCasa: 'Vencedor Jogo 7', golsCasa: '',timeFora: 'Vencedor Jogo 8', fotoFora:'', golsFora: ''},
    {fase:'7ª Lugar', rodada:8,jogo:72,hora:'17:00',mesa: 8,fotoCasa:'', timeCasa: 'Perdedor Jogo 7', golsCasa: '',timeFora: 'Perdedor Jogo 8', fotoFora:'', golsFora: ''},
]
