import { Curso } from "../model/Curso.js"

export let cursos = [
  new Curso('Curso em Vídeo', 'P.H.P. com M.Y.S.Q.L. - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/validacao-de-certificado/.hncvfl_form_input_text=11', new Date('02/03/2022'), new Date('03/03/2022')),
  new Curso('Curso em Vídeo', 'P.H.P. com M.Y.S.Q.L. - Módulo 01 - Criando um C.R.U.D.', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/04/2022'), new Date('03/04/2022')),
  new Curso('Curso em Vídeo', 'P.H.P. com M.Y.S.Q.L. - Módulo 02 - Segurança e níveis de acessso', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/05/2022'), new Date('03/05/2022')),
  new Curso('Curso em Vídeo', 'Desenvolvimento Web 2020 ( HTML5+CSS3 ) Módulo 01',  'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/23/2022'), new Date('03/23/2022')),
  new Curso('Curso em Vídeo', 'Desenvolvimento Web 2020 ( HTML5+CSS3 ) Módulo 02', 'https://www.estudonauta.com/validacao-de-certificado/',  new Date('02/26/2022'), new Date('03/26/2022')),
  new Curso('Curso em Vídeo', 'Desenvolvimento Web 2020 ( HTML5+CSS3 ) Módulo 03', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/27/2022'), new Date('03/27/2022')),
  new Curso('Curso em Vídeo', 'Javascript', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/27/2022'), new Date('03/29/2022')),   
  new Curso('Curso em Vídeo', 'Java básico - Módulo 00', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/27/2022'), new Date('03/30/2022')),
  new Curso('Curso em Vídeo', 'Java P.O.O. - Módulo 00', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/27/2022'), new Date('03/30/2022')),          
  new Curso('Curso em Vídeo', 'WordPress com Gutemberg - modulo 01 - Criação de Site', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/02/2022'), new Date('04/02/2022')),
  new Curso('Curso em Vídeo', 'WordPress com Gutemberg - modulo 02 - Segurança e Performance', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/03/2022'), new Date('04/03/2022')),
  new Curso('Curso em Vídeo', 'WordPress + WooCommerce - modulo 03 - Criação de Loja com WooCommerce', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/06/2022'), new Date('04/06/2022')),
  new Curso('Curso em Vídeo', 'P.H.P. básico', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/25/2022'), new Date('04/25/2022')),
  new Curso('Curso em Vídeo', 'P.H.P. P.O.O.', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/29/2022'), new Date('04/29/2022')),
  new Curso('Curso em Vídeo', 'P.H.P. moderno modulo 01', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('03/26/2022'), new Date('04/26/2022')),
  new Curso('Curso em Vídeo', 'MYSQL - Modulo 00', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('04/02/2022'), new Date('05/02/2022')), 
  new Curso('Curso em Vídeo', 'Modulo 00 - Segurança da Informação - Pilares e principais Riscos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('05/10/2022'), new Date('06/10/2022')),
  new Curso('Curso em Vídeo', 'Modulo 01 - Segurança da Informação - Redes Sociais, senhas e verificação em duas etapas', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('05/10/2022'), new Date('06/10/2022')), 
  new Curso('Curso em Vídeo', 'Desenvolvimento Web 2020 ( HTML5+CSS3 ) Módulo 04',  'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/03/2022'), new Date('08/03/2022')),          
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 00 - Fundamentos de Rede', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/12/2022'), new Date('08/12/2022')),
  new Curso('Curso em Vídeo', 'Android - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/20/2022'), new Date('08/20/2022')),
  new Curso('Curso em Vídeo', 'Android - Módulo 01 - Estruturas Básicas', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/20/2022'), new Date('08/20/2022')),
  new Curso('Curso em Vídeo', 'Android - Módulo 02 - Interfaces', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/23/2022'), new Date('08/23/2022')),
  new Curso('Curso em Vídeo', 'Android - Módulo 03 - Atividades', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/25/2022'), new Date('08/25/2022')),
  new Curso('Curso em Vídeo', 'Kotlin - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/25/2022'), new Date('08/25/2022'),),
  new Curso('Curso em Vídeo', 'Kotlin - Módulo 01 - Estruturas Básicas', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/30/2022'), new Date('08/30/2022')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 01 - Cabeamento', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/03/2022'), new Date('09/03/2022')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 02 - TCP/IP e WI-FI', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/03/2022'), new Date('09/03/2022')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 03 - Endereçamento IP', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/07/2022'), new Date('09/07/2022')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 04 - Equipamentos de Rede', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/08/2022'), new Date('09/08/2022')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 05 - Protocolos e Modelos OSI', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/09/2022'), new Date('09/09/2022')),
  new Curso('Curso em Vídeo', 'Arquitetura de Computadores - Módulo 00', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/18/2022'), new Date('09/18/2022')),
  new Curso('Curso em Vídeo', 'C - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/certificates/certificado-20h/?course_id=46705&cert-nonce=e02c6d58fc', new Date('08/20/2022'), new Date('09/20/2022')),
  new Curso('Curso em Vídeo', 'C - Módulo 01 - Estruturas Básicas', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('08/28/2022'), new Date('09/28/2022')),
  new Curso('Curso em Vídeo', 'Arquitetura de Computadores - Módulo 01', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/18/2022'), new Date('11/18/2022')), 
  new Curso('Curso em Vídeo', 'Raspberry Pi - Módulo 00 - Conhecendo o Raspberry Pi', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('12/01/2022'), new Date('01/01/2023')),
  new Curso('Curso em Vídeo', 'Raspberry Pi - Módulo 01 - Programando com Raspberry Pi', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('12/02/2022'), new Date('01/02/2023')),
  new Curso('Curso em Vídeo', 'Raspberry Pi - Módulo 02 - Raspberry Pi Avaçado', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('12/03/2022'), new Date('01/03/2023')),
  new Curso('Curso em Vídeo', 'Raspberry Pi - Módulo 03 - Retro Gaming com Raspberry Pi', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('12/08/2022'), new Date('01/08/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/21/2023'), new Date('02/21/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 01 - Interface and Terminal', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/21/2023'), new Date('02/21/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 02 - Pacotes e gestão de Processos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/22/2023'), new Date('02/22/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 03 - Programação com Linux', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/23/2023'), new Date('02/23/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 04 - Terminal Avançado', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/25/2023'), new Date('02/25/2023')),
  new Curso('Curso em Vídeo', 'Linux - Módulo 05 - Discos e Raid', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('01/26/2023'), new Date('02/26/2023')),
  new Curso('Curso em Vídeo', 'Eletrônica Básico - Módulo 00 - Fundamentos da Eletrônica', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/25/2023'), new Date('03/25/2023')),
  new Curso('Curso em Vídeo', 'Eletrônica Básico - Módulo 01 - Criando Circuito', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('02/25/2023'), new Date('03/25/2023')),
  new Curso('Curso em Vídeo', 'Python - Mundo 01 - Fundamentos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('04/01/2023'), new Date('05/01/2023')),       
  new Curso('Curso em Vídeo', 'Python - Mundo 02 - Estrutura de controle', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('04/01/2023'), new Date('05/01/2023')),          
  new Curso('Curso em Vídeo', 'Python - Mundo 03 - Estrutura compostas', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('04/01/2023'), new Date('05/01/2023')),   
  new Curso('Curso em Vídeo', 'Arquitetura de Computadores - Módulo 02', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('04/16/2023'), new Date('05/16/2023')),
  new Curso('Curso em Vídeo', 'S.E.O. - Módulo 01', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('05/24/2023'), new Date('06/24/2023')),
  new Curso('Curso em Vídeo', 'WordPress - modulo 04 - Adequando Sites e Lojas Virtuais em Wordpress a LGPD', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('06/11/2023'), new Date('07/11/2023')),  
  new Curso('Curso em Vídeo', 'S.E.O. - Módulo 02',  'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/13/2023'), new Date('08/13/2023')),
  new Curso('Curso em Vídeo', 'Git - Github', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/01/2023'), new Date('11/01/2023'),),
  //new Curso('Curso em Vídeo', 'Inteligência Artificial - Módulo 01', '', new Date('11/11/2024'), new Date('11/12/2024')),      
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 01 - Cámeras', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 02 - Iluminação', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 03 - Audio com qualidade', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 04 - Edição de Vídeos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 05 - Criando uma Thumb', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Produção de Vídeos - Módulo 06 - Animação', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('10/19/2023'), new Date('11/19/2023')),
  new Curso('Curso em Vídeo', 'Redes de Computadores - Módulo 06 - Transmissão de Sinal', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('06/05/2025'), new Date('07/05/2025')),
  new Curso('Curso em Vídeo', 'C - Módulo 02 - Operatores', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/22/2025'), new Date('08/22/2025')),
  new Curso('Curso em Vídeo', 'C - Módulo 03 - Estrutura de Controle ( Condições )', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/23/2025'), new Date('08/23/2025')),
  new Curso('Curso em Vídeo', 'C# - Módulo 00 - Primeiros Passos', 'https://www.estudonauta.com/validacao-de-certificado/', new Date('07/23/2025'), new Date('08/23/2025')),
]