import { Projeto } from '../model/Projeto.js'

export let projetos = [
  new Projeto( 2022, 'Projeto de Vídeos', 'Projeto construido para treinar a inserção de vídeos em nosso site.', 'Este é um pequeno site que funciona como uma galeria de vídeos. Na página inicial, você encontrará quatro opções de vídeos sobre diferentes temas: Hardware, HTML, JavaScript e Python. Para assistir a um vídeo, basta clicar na imagem de miniatura correspondente. Você será levado a uma nova página onde o vídeo estará disponível. Depois de assistir, você pode usar o botão "voltar" para retornar à página principal e escolher outro vídeo.', './imagens/projeto-01-videos.jpg', '../d009/index.html'),
  new Projeto( 2023, 'Projeto Cordel', 'Projeto construido para treinar efeito paralax em imagens.', 'Explore um site envolvente dedicado à rica tradição do cordel moderno. Navegue por conteúdo inspirador e desfrute de uma experiência visualmente agradável, projetada com cuidado para uma leitura confortável e imersiva. Ideal para apreciadores da cultura e poesia popular.', './imagens/projeto-02-cordel.jpg', '../d012/index.html'),
  new Projeto( 2022, 'Projeto Android', 'Projeto construido para treinar conteúdos e imagens dinâmicas.', 'O objetivo foi criar uma página web responsiva sobre a história do mascote do Android, aplicando conceitos de HTML semântico e CSS. Para isso, utilizei estilização customizada, importação de fontes externas e organizei o conteúdo para recriar um layout específico, demonstrando habilidades em estruturação e design de páginas web.', './imagens/projeto-03-android.jpg', '../d010/index.html'),
  new Projeto( 2022, 'Projeto Links', 'Projeto construido para treinar tela de links.', 'Esta página apresenta um celular interativo. Clique em um dos logotipos no menu para abrir o perfil correspondente na tela e conhecer mais sobre meu trabalho e projetos.', './imagens/projeto-04-links.jpg', '../d015/index.html'),
  new Projeto( 2022, 'Projeto Login', 'Projeto construido para treinar tela de login.', 'Este é um exercício prático de desenvolvimento web, focado na construção de uma página HTML estilizada com CSS. O projeto destaca a implementação de design responsivo usando media queries para garantir uma boa experiência de visualização em múltiplos dispositivos, além de organizar os estilos em arquivos separados para melhor manutenção. Inclui também o uso de uma imagem para compor o visual da página.', './imagens/projeto-05-login.jpg', '../d016/index.html'),
  new Projeto( 2022, 'Projeto Album', 'Projeto construido para treinar album com imagens.', 'Bem-vindo à nossa galeria! Explore uma coleção de imagens variadas, cuidadosamente apresentadas para você. Esta página foi desenhada para se adaptar perfeitamente ao tamanho da sua tela, garantindo a melhor experiência de visualização, seja no computador, no tablet ou no celular.', './imagens/projeto-06-album.jpg', '../d017/index.html'),
  new Projeto( 2025, 'Votos: Análise Parlamentar Personalizada', 'Projeto construido para treinar Apis.', 'Este projeto oferece uma plataforma interativa para que você possa explorar e analisar o cenário político brasileiro de forma personalizada. Com ele, você pode selecionar deputados, partidos e leis de seu interesse, configurar suas preferências e realizar análises comparativas.', './imagens/projeto-07-album.jpg', '../../../../pessoal/votos/index.html'),
  new Projeto( 2025, 'Projetos da Lei Rouanet', 'Projeto construido para treinar Apis.', 'A aplicação web permite a visualização de dados relacionados a projetos incentivados pela Lei Rouanet. É possível navegar entre diferentes categorias, como proponentes, incentivadores, fornecedores, propostas e projetos. Além disso, a aplicação oferece a funcionalidade de filtrar os resultados para facilitar a busca por informações específicas.', './imagens/projeto-08-album.jpg', '../../../../pessoal/lei-incentivo/index.html'),
  new Projeto( 2025, 'Temperatura', 'Projeto construido para treinar Apis.', 'A aplicação permite que o usuário insira o nome de uma cidade e visualize dados climáticos como temperatura, condições do tempo, umidade e velocidade do vento. Os dados são obtidos através da API do OpenWeatherMap.', './imagens/projeto-09-album.jpg', '../../../../pessoal/temperatura/index.html'),
  new Projeto( 2025, 'Curriculo', 'Projeto construido para apresentar o curriculo.', 'Mostra meu curriculo e três idiomas.', './imagens/projeto-10-album.jpg', '../../../../pessoal/apresentacao/curriculo.html'),
]