export let sujestaoCompras = [
    { produto: 'Arroz', quantidade: 5 },
    { produto: 'Feijão', quantidade: 4 },
    { produto: 'Açúcar', quantidade: 3 },
    { produto: 'Sal', quantidade: 1 },
    { produto: 'Óleo', quantidade: 2 },
    { produto: 'Macarrão', quantidade: 4 },
    { produto: 'Farinha de Trigo', quantidade: 2 },
    { produto: 'Café', quantidade: 2 },
    { produto: 'Leite', quantidade: 15 },
    { produto: 'Manteiga', quantidade: 2 },
    { produto: 'Tomate', quantidade: 8 },
    { produto: 'Cebola', quantidade: 6 },
    { produto: 'Alho', quantidade: 2 },
    { produto: 'Batata', quantidade: 6 },
    { produto: 'Banana', quantidade: 20 },
    { produto: 'Frango', quantidade: 4 },
    { produto: 'Carne Bovina', quantidade: 4 },
    { produto: 'Ovos', quantidade: 4 },
    { produto: 'Amaciante', quantidade: 4 },
    { produto: 'Detergente', quantidade: 4 },
    { produto: 'Sabão em Pó', quantidade: 2 },
    { produto: 'Desinfetante', quantidade: 2 },
    { produto: 'Água Sanitária', quantidade: 2 },
    { produto: 'Esponja', quantidade: 4 },
    { produto: 'Papel Higiênico', quantidade: 16 },
    { produto: 'Saco de Lixo', quantidade: 3 },
    { produto: 'Sabonete', quantidade: 6 },
    { produto: 'Shampoo', quantidade: 2 },
    { produto: 'Condicionador', quantidade: 2 },
    { produto: 'Creme Dental', quantidade: 3 },
    { produto: 'Fio Dental', quantidade: 2 },
    { produto: 'Desodorante', quantidade: 4 },
    { produto: 'Papel Toalha', quantidade: 4 },
    { produto: 'Absorvente', quantidade: 2 },
    { produto: 'Aparelho de Barbear', quantidade: 2 }
];
